services:
  planning-poker-prod-like:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: planning-poker-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    volumes:
      - "./${UPLOAD_DIR}:/app/${UPLOAD_DIR}"
      - "./data:/app/data"
      - "./db:/app/db"

  mailcatcher:
    container_name: planning-poker-mail-catcher
    image: sj26/mailcatcher
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP
    restart: unless-stopped