import type {Metadata} from "next";
import "./../globals.css";
import * as React from "react";
import {AppSidebar} from "@/components/navigation/app-sidebar";
import {SidebarInset, SidebarProvider} from "@/components/ui/sidebar";
import {AppHeader} from "@/components/navigation/app-header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <SidebarProvider>
            <AppSidebar/>
            <SidebarInset>
                <AppHeader/>
                {children}
            </SidebarInset>
        </SidebarProvider>
    );
}