import type {Metadata} from "next";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";
import * as React from "react";
import {ThemeProvider} from "next-themes";
import SessionProvider from "@/components/auth/session-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    icons: [
        {
            url: "/icons/favicon.ico",
            sizes: "8x8",
            type: "image/x-icon",
        },
    ]
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body>
        <SessionProvider>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {children}
                <Toaster/>
            </ThemeProvider>
        </SessionProvider>
        </body>
        </html>
    );
}